### ISSUE TITLE
plugin.info.txt is missing

### ISSUE THREAD

**Issue by bigwasp** [zioth/dokuwik-anchor#1]
Hi!
Thanks for your Plugin!
It is not a real issue, but it seems without plugin.info.txt DW shows the Plugins
as updatable, but using the newest version.

https://www.dokuwiki.org/devel:plugin_info
imho getInfo() is no more needed

regards
bigwasp

**Comment by zioth** [comment]
I used getInfo instead of plugin.info.txt because this is an extremely simple plugin that I wanted to keep to one file. The real issue was that getInfo() returned a different date than the one on dokuwiki.org. It's fixed now. If you update the plugin, the upgrade notice should go away.
