### ISSUE TITLE
Stable tags and releases

### ISSUE THREAD

**Issue by stefan-as** [zioth/dokuwik-anchor#2]
Can we please have git tags and stable releases for this DokuWiki plugin? It is not easy to maintain a stable DokuWiki instance including your plugin, if there is no possibility to pin your plugin to a specific version.

The tag plugin, for example, distributes stable releases on their github page: https://github.com/dokufreaks/plugin-tag/releases

**Comment by zioth** [comment]
This is such a simple plugin, and I think I've updated it only twice in the last ten years, so stable releases aren't going to be very helpful. You can assume that every release of this plugin is a stable release, and works with every version of DokuWiki from the past decade.

Stable releases could be a good idea for some of my more complex plugins, especially [FastWiki](https://github.com/zioth/dokuwiki-fastwiki).
