### ISSUE TITLE
Plugin is updated but still says, that a new version is available

### ISSUE THREAD

**Issue by fthommen** [zioth/dokuwik-anchor#4]
Hi,

even though I have updated the plugin (several times :-) it still complains that a newer version is available:

![image](https://user-images.githubusercontent.com/279232/136619774-fbf7860b-d020-4c55-bb02-77cf8036b8e2.png)

**Comment by zioth** [comment]
Maybe the getInfo() function doesn't work anymore. I've added plugin.info. Try it now.

**Comment by fthommen** [comment]
Works now.  Thanks a lot.
