### ISSUE TITLE
Deprecation warning require

### ISSUE THREAD

**Issue by Miro-Collas** [zioth/dokuwik-anchor#6]
With PHP 8.1:

`2023-08-13 06:54:25             require(syntax.php) is deprecated. It was called from require() in /home/fswiki/public_html/lib/plugins/anchor/syntax.php:4 Autoloading should be used instead
!`

Removing the line _seems_ to fix the problem.

**Comment by yaynstuff** [comment]
Can the author please confirm if this was the right thing to do? I was the one (I am the projects sysadmin) who attempted this to squelch the warning this way, I did so on a whim by looking at some example syntax plugins in the docuwiki developer resources and notices that this require line is not present.

**Comment by zioth** [comment]
If it still works after removing that line, great! I'm hesitant to remove it from the main source, because:
1) I'm not sure which versions of PHP support autoloaders, and I don't want my plugins to stop working for some people.
2) This line can be found in many dokuwiki plugins work.

I'll keep this issue open so I can investigate it at some point.

**Comment by Miro-Collas** [comment]
> If it still works after removing that line, great! I'm hesitant to remove it from the main source, because:
> 
>     1. I'm not sure which versions of PHP support autoloaders, and I don't want my plugins to stop working for some people.
> 
>     2. This line can be found in many dokuwiki plugins work.
> 
> 
> I'll keep this issue open so I can investigate it at some point.

Yes, many plugins do use it, and it seems they're all throwing the same error. To give just one example:
https://github.com/zioth/dokuwiki-anchor/issues/6

**Comment by Miro-Collas** [comment]
I just spotted this, which didn't show last night - possibly because at the time, no one was accessing a page that referenced anchor:

`2023-08-13 21:34:27E_WARNING: Undefined array key 1/home/fswiki/public_html/lib/plugins/anchor/syntax.php(31)
    #0 /home/fswiki/public_html/lib/plugins/anchor/syntax.php(31): dokuwiki\ErrorHandler::errorHandler(2, 'Undefined array...', '/home/fswiki/pu...', 31)
    #1 /home/fswiki/public_html/inc/parser/renderer.php(119): syntax_plugin_anchor->render('xhtml', Object(Doku_Renderer_xhtml), Array)
    #2 /home/fswiki/public_html/inc/parserutils.php(700): Doku_Renderer->plugin('anchor', Array, 5, '{{anchor:dullah...')
    #3 /home/fswiki/public_html/inc/parserutils.php(158): p_render('xhtml', Array, NULL)
    #4 /home/fswiki/public_html/inc/parserutils.php(96): p_cached_output('/home/fswiki/pu...', 'xhtml', 'fs_media')
    #5 /home/fswiki/public_html/inc/Ui/PageView.php(68): p_wiki_xhtml('fs_media', 0, true, '')
    #6 /home/fswiki/public_html/inc/Action/Show.php(37): dokuwiki\Ui\PageView->show()
    #7 /home/fswiki/public_html/inc/template.php(100): dokuwiki\Action\Show->tplContent()
    #8 [internal function]: tpl_content_core('show')
    #9 /home/fswiki/public_html/inc/Extension/Event.php(133): call_user_func_array('tpl_content_cor...', Array)
    #10 /home/fswiki/public_html/inc/Extension/Event.php(199): dokuwiki\Extension\Event->trigger('tpl_content_cor...', true)
    #11 /home/fswiki/public_html/inc/template.php(85): dokuwiki\Extension\Event::createAndTrigger('TPL_ACT_RENDER', 'show', 'tpl_content_cor...')
    #12 /home/fswiki/public_html/lib/tpl/bootstrap3/main.php(117): tpl_content(false)
    #13 /home/fswiki/public_html/inc/actions.php(27): include('/home/fswiki/pu...')
    #14 /home/fswiki/public_html/doku.php(126): act_dispatch()
    #15 {main}`

**Comment by yaynstuff** [comment]
> If it still works after removing that line, great! I'm hesitant to remove it from the main source, because:
> 
>     1. I'm not sure which versions of PHP support autoloaders, and I don't want my plugins to stop working for some people.
> 
>     2. This line can be found in many dokuwiki plugins work.
> 
> 
> I'll keep this issue open so I can investigate it at some point.

As per https://www.dokuwiki.org/devel:releases:refactor2020#general_cleanup_suggestions it suggests it can probably be removed safely and is not needed in most cases?

**Comment by yaynstuff** [comment]
> I just spotted this, which didn't show last night - possibly because at the time, no one was accessing a page that referenced anchor:
> 
> `2023-08-13 21:34:27E_WARNING: Undefined array key 1/home/fswiki/public_html/lib/plugins/anchor/syntax.php(31) #0 /home/fswiki/public_html/lib/plugins/anchor/syntax.php(31): dokuwiki\ErrorHandler::errorHandler(2, 'Undefined array...', '/home/fswiki/pu...', 31) #1 /home/fswiki/public_html/inc/parser/renderer.php(119): syntax_plugin_anchor->render('xhtml', Object(Doku_Renderer_xhtml), Array) #2 /home/fswiki/public_html/inc/parserutils.php(700): Doku_Renderer->plugin('anchor', Array, 5, '{{anchor:dullah...') #3 /home/fswiki/public_html/inc/parserutils.php(158): p_render('xhtml', Array, NULL) #4 /home/fswiki/public_html/inc/parserutils.php(96): p_cached_output('/home/fswiki/pu...', 'xhtml', 'fs_media') #5 /home/fswiki/public_html/inc/Ui/PageView.php(68): p_wiki_xhtml('fs_media', 0, true, '') #6 /home/fswiki/public_html/inc/Action/Show.php(37): dokuwiki\Ui\PageView->show() #7 /home/fswiki/public_html/inc/template.php(100): dokuwiki\Action\Show->tplContent() #8 [internal function]: tpl_content_core('show') #9 /home/fswiki/public_html/inc/Extension/Event.php(133): call_user_func_array('tpl_content_cor...', Array) #10 /home/fswiki/public_html/inc/Extension/Event.php(199): dokuwiki\Extension\Event->trigger('tpl_content_cor...', true) #11 /home/fswiki/public_html/inc/template.php(85): dokuwiki\Extension\Event::createAndTrigger('TPL_ACT_RENDER', 'show', 'tpl_content_cor...') #12 /home/fswiki/public_html/lib/tpl/bootstrap3/main.php(117): tpl_content(false) #13 /home/fswiki/public_html/inc/actions.php(27): include('/home/fswiki/pu...') #14 /home/fswiki/public_html/doku.php(126): act_dispatch() #15 {main}`

This line of code seems to be triggering it, specifically data[1] -- but I do not know why... Any thoughts?

`                $renderer->doc .= '<a name="' . $data[0] . '">' . $data[1] . '</a>';`

**Comment by Miro-Collas** [comment]
> If it still works after removing that line, great! I'm hesitant to remove it from the main source, because:
> 
>     1. I'm not sure which versions of PHP support autoloaders, and I don't want my plugins to stop working for some people.
> 
>     2. This line can be found in many dokuwiki plugins work.
> 
> 
> I'll keep this issue open so I can investigate it at some point.

Regarding the require, ref https://www.dokuwiki.org/devel:releases:refactor2020#general_cleanup_suggestions

**Comment by yaynstuff** [comment]
My PHP is pretty rusty, but wouldnt it be good practice to check if the array key exists first rather than make an assumption? ie: use array_key_exists() or isset() ?

**Comment by zioth** [comment]
Sure. I wrote the plugin for myself, and then published it as a simple example to help others develop syntax plugins. I'm not surprised that there's an issue or two, but it is surprising that it took this long for them to come up! :) I wonder if php's strict mode around arrays changed in the last 4 versions.

I can try to fix this sometime soon. In the mean time, I wonder if you are using the plugin around empty content. That might cause [1] not to exist.

**Comment by zioth** [comment]
Fixed both issues.

**Comment by Miro-Collas** [comment]
> Sure. I wrote the plugin for myself, and then published it as a simple example to help others develop syntax plugins. I'm not surprised that there's an issue or two, but it is surprising that it took this long for them to come up! :) I wonder if php's strict mode around arrays changed in the last 4 versions.
> 
> I can try to fix this sometime soon. In the mean time, I wonder if you are using the plugin around empty content. That might cause [1] not to exist.

Thanks for the fixes! :-)

I think one reason it has taken so long to crop up is that many haven't yet updated their Dokuwiki installs, per [this](https://www.dokuwiki.org/popularity). We only did it 2 days ago, due to a bug in a different plugin that was throwing errors during the upgrade process.
