### ISSUE TITLE
Warning in info/syntax.php

### ISSUE THREAD

**Issue by Miro-Collas** [zioth/dokuwik-anchor#7]
Please see the discussion at https://github.com/dokuwiki/dokuwiki/issues/4033 - apparently the root cause is a problem with this plugin.

**Comment by fiwswe** [comment]
This was fixed in version 2023-08-14.

Please update your plugin.

**Comment by Miro-Collas** [comment]
My apologies for my error.

**Comment by zioth** [comment]
@Miro-Collas No error. The bug was just fixed a couple days ago. I'm not surprised you didn't have the latest version. :)
