### ISSUE TITLE
Anchor Plugin incorrectly sets line break

### ISSUE THREAD

**Issue by ACX-Com** [zioth/dokuwik-anchor#8]
Example:
Anchor incorrectly puts line break in enum:

Editing area:
  - test1 {{anchor:a_name1:}} test2

...here a line break is placed before test2.
Even if you use ...a_name1 or ...a_name1:test.

**Comment by tosterdev** [comment]
[Check my fork](https://github.com/Andrew1481432/dokuwiki-anchor) my changes fixed it

**Comment by zioth** [comment]
Thanks! I've incorporated your fork, with a few changes to handle the case where the third param isn't included.
